name: Deploy Static Site to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.GCP_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy static files via rsync
      run: |
        rsync -avz --delete \
          -e "ssh -i ~/.ssh/id_ed25519" \
          ./ ${{ secrets.GCP_USER }}@${{ secrets.GCP_HOST }}:${{ secrets.GCP_TARGET_DIR }}
